name: pr-ai_app_94531f9_env_3d531e8 Pipeline (Skyu Generated)
'on':
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_5f36fa7d-9c17-4c99-a63f-80f84afcf562
env:
  ENCODED_PIPELINE_SECRET: ${{secrets.TESTSERVICE2_PRAI_APP_94531F9_ENV_3D531E8}}
  COMMIT_ID: ${{github.event.client_payload.commitId || github.sha || github.run_id}}
jobs:
  _status-pending:
    name: _status Pending
    permissions: write-all
    env:
      CONTEXT_JSON: ${{ toJson(github) }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Run :: Decoding Secrets'
        run: |2-

                if [ ! -x "$(command -v jq)" ]; then
                  echo "jq not found, installing..."
                  sudo apt-get update
                  sudo apt-get install -y jq
                fi
                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: Pipeline Started
        run: |2-

              context=$(echo '${{ env.CONTEXT_JSON }}' | jq -c . | base64)
              response=$(curl -X PUT -d "runId=${{ github.run_id }}&context=$context"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  '${{ env.PIPELINE_SERVICE_EP }}/${{ env.PIPELINE_ID }}/PENDING?releaseId=${{ github.event.client_payload.releaseData.releaseId }}')
              if echo "$response" | grep -q '"success":true'; then
                echo "SUCCESS :: $response"
              else
                echo "FAILED :: $response"
              fi
              
  fix-code-with-ai:
    name: Fix Code With AI
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 'Run :: Check Logs'
        id: check-logs
        env:
          LOGS: ${{ github.event.client_payload.logs }}
        run: |2-

                  if ${{ env.LOGS != null }}; then
                    echo "Logs found..."
                    echo "Logs: ${{ env.LOGS }}"
                  else 
                    echo "Logs Not found to run the AI pipeline"
                    exit 1
                  fi
                
      - name: 'Run :: Decoding Secrets'
        run: |2-

                if [ ! -x "$(command -v jq)" ]; then
                  echo "jq not found, installing..."
                  sudo apt-get update
                  sudo apt-get install -y jq
                fi
                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: 'Run :: Checkout repository for AI Fixes'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Run :: Get file paths'
        id: get-file-paths
        run: |2-

                  files="$(git ls-files -z | tr '\0' ,)"
                  echo "file-paths=$files" >> $GITHUB_OUTPUT
                
      - name: 'Run :: Send logs to AI service'
        id: send-logs
        env:
          LOGS: ${{ github.event.client_payload.logs }}
          FILE_PATHS: ${{ steps.get-file-paths.outputs.file-paths }}
        run: |2-

                  payload=$(jq -n --arg logs "${{ env.LOGS }} | @sh" --arg file_paths "$FILE_PATHS" '{"error_message": $logs, "available_files": $file_paths}')
                  echo "payload: $payload"

                  response=$(curl -X POST -d "$payload"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-auth-by: sa' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'Content-Type: application/json'  '${{ env.AI_SUGGESTED_SOLUTION_EP }}/identify-files/')

                  status_code=$?
                  if [ $status_code -eq 0 ]; then
                    echo "SUCCESS :: $response"
                    identifiedFiles=$(echo "$response" | jq -r '.identified_files')
                  echo "identified-files=$identifiedFiles" >> $GITHUB_OUTPUT
                  else
                    echo "FAILED :: $response"
                    exit 1
                  fi
                  
      - name: 'Run :: Create new branch'
        run: git checkout -b fix-issue-${{ github.run_id }}
      - name: 'Run :: Send file to AI Service'
        id: send-file
        env:
          LOGS: ${{ github.event.client_payload.logs }}
          FILE_NAME: ${{ steps.send-logs.outputs.identified-files }}
          FILE_PATH: ${{ steps.send-logs.outputs.identified-files }}
        run: |2-

                  file_content=$(cat "$FILE_PATH")
                  payload=$(jq -n --arg fileName "$FILE_NAME" --arg fileContent "$file_content" --arg logs "${{ env.LOGS }} | @sh" '{"code_dict": {($fileName): $fileContent}, "error_log": $logs}')
                  echo "payload: $payload"

                  response=$(curl -X POST -d "$payload"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-auth-by: sa' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'Content-Type: application/json'  '${{ env.AI_SUGGESTED_SOLUTION_EP }}/fix-errors/')

                  task_id=$(echo "$response" | jq -r '.task_id')
                  echo "Task ID: $task_id"
                  task_status="pending"

                  while ["$task_status" != "completed"]; do
                    final_response=$(curl -X GET -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-auth-by: sa' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'Content-Type: application/json'  '${{ env.AI_SUGGESTED_SOLUTION_EP }}/fix-errors/$task_id')

                    task_status=$(echo "$final_response" | jq -r '.status')

                    if [ "$task_status" != "completed" ]; then
                    echo "Task $task_status ..."
                    sleep 10  
                    else
                      echo "Task done... Proceeding"
                      break
                    fi
                  done

                  status_code=$?
                  if [ $status_code -eq 0 ]; then
                    echo "SUCCESS :: $final_response"
                    correction_files=$(echo "${final_response}" | jq -r '.result')

                    # Loop through the JSON object
                    echo "${correction_files}" | jq -r 'to_entries[] | @base64' | while read -r line; do
                        # Decode the base64 to get the original JSON string
                        decoded=$(echo "${line}" | base64 --decode)
                        # Extract the key (filename) and value (file content) using jq
                        key=$(echo "${decoded}" | jq -r '.key')
                        value=$(echo "${decoded}" | jq -r '.value')
                        # Use the key as the filename and the value as the content, writing to the file
                        echo "${value}" > "${key}"
                        echo "Written to ${key}"
                    done
                  
                    echo "All files have been created."
                    echo "identified-files=$identifiedFiles" >> $GITHUB_OUTPUT
                  else
                    echo "FAILED :: $final_response"
                    exit 1
                  fi
                
      - name: 'Run :: Commit changes'
        run: |2-

                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Actions"
                  git add .
                  git commit -m "fix issue"
                
      - name: 'Run :: Push changes'
        run: git push origin fix-issue-${{ github.run_id }}
      - name: 'Run :: Create Pull Request'
        uses: repo-sync/pull-request@v2
        with:
          source_branch: fix-issue-${{ github.run_id }}
          destination_branch: main
          pr_title: Fix Issue-${{ github.run_id }}
          pr_body: This pull request fixes the error contained in the logs.
          github_token: ${{ secrets.GITHUB_TOKEN }}
  _status-success:
    name: _status Success
    permissions: write-all
    env:
      CONTEXT_JSON: ${{ toJson(github) }}
    runs-on: ubuntu-latest
    needs:
      - fix-code-with-ai
    if: ${{ !(failure() || cancelled()) }}
    steps:
      - name: 'Run :: Decoding Secrets'
        run: |2-

                if [ ! -x "$(command -v jq)" ]; then
                  echo "jq not found, installing..."
                  sudo apt-get update
                  sudo apt-get install -y jq
                fi
                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: Pipeline Success
        run: |2-

              context=$(echo '${{ env.CONTEXT_JSON }}' | jq -c . | base64)
              response=$(curl -X PUT -d "runId=${{ github.run_id }}&context=$context"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  '${{ env.PIPELINE_SERVICE_EP }}/${{ env.PIPELINE_ID }}/SUCCESS?releaseId=${{ github.event.client_payload.releaseData.releaseId }}')
              
  _status-failed:
    name: _status Failed
    permissions: write-all
    env:
      CONTEXT_JSON: ${{ toJson(github) }}
    runs-on: ubuntu-latest
    needs:
      - fix-code-with-ai
    if: ${{ failure() || cancelled() }}
    steps:
      - name: 'Run :: Decoding Secrets'
        run: |2-

                if [ ! -x "$(command -v jq)" ]; then
                  echo "jq not found, installing..."
                  sudo apt-get update
                  sudo apt-get install -y jq
                fi
                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: Pipeline Failed
        run: |2-

              context=$(echo '${{ env.CONTEXT_JSON }}' | jq -c . | base64)
              response=$(curl -X PUT -d "runId=${{ github.run_id }}&context=$context"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  '${{ env.PIPELINE_SERVICE_EP }}/${{ env.PIPELINE_ID }}/FAILED?releaseId=${{ github.event.client_payload.releaseData.releaseId }}')
              
